# Generated by Django 3.0.7 on 2020-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geo_sectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('country_name', models.CharField(max_length=50, null=True)),
                ('sector_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
